### ISSUE TITLE
cDock 9

### ISSUE THREAD

**Issue by w0lfschild** [w0lfschild/cDock#16]
Post here if you're having issues with cDock 9. Please read this first before making your own posting. 

----

If you're running 10.11 make sure you've turned off System Integrity Protection

> System Integrity Protection can be disabled completely by booting into the recovery system and disabling it with the security configuration utility.

----

If cDock is not working make sure these 2 files are in place

    /Library/Application Support/SIMBL/Plugins/cDock.bundle
    /System/Library/ScriptingAdditions/SIMBL.osax

**Comment by Wallyec** [comment]
ver 9.12 Does not work on X10.11 Beta (15A234d) - latest build i have access to - tried reloading, reset, different settings but no go.

Could not find any of the items listed for console.app - not that familiar but search did not find any ref to cdock.

Sorry.

**Comment by Wallyec** [comment]
more info ...

Jul 29 18:01:27 MacBook-Pro bird[276]: LaunchServices: Failed to create bundleProxy for bundle org.w0lf.cDock
Jul 29 18:05:00 MacBook-Pro cDock Agent[681]: SecTaskLoadEntitlements failed error=22
Jul 29 18:05:00 MacBook-Pro cDock Agent[681]: App did finish launching
Jul 29 18:13:32 MacBook-Pro cDock Agent[341]: SecTaskLoadEntitlements failed error=22
Jul 29 18:13:32 MacBook-Pro cDock Agent[341]: App did finish launching
Jul 29 18:15:56 MacBook-Pro cDock[815]: SecTaskLoadEntitlements failed error=22
Jul 29 18:15:56 MacBook-Pro cDock[815]: App did finish launching
Jul 29 18:16:03 MacBook-Pro com.apple.xpc.launchd[1] (org.w0lf.cDock.219872[815]): Service exited due to signal: Terminated: 15
Jul 29 18:16:07 MacBook-Pro cDock[1355]: SecTaskLoadEntitlements failed error=22
Jul 29 18:16:07 MacBook-Pro cDock[1355]: App did finish launching
Jul 29 18:16:23 MacBook-Pro com.apple.xpc.launchd[1] (org.w0lf.cDockAgent.134112[341]): Service exited due to signal: Killed: 9
Jul 29 18:16:33 MacBook-Pro cDock[1939]: SecTaskLoadEntitlements failed error=22
Jul 29 18:16:33 MacBook-Pro cDock[1939]: App did finish launching
Jul 29 18:16:33 MacBook-Pro cDock Agent[2082]: SecTaskLoadEntitlements failed error=22
Jul 29 18:16:34 MacBook-Pro cDock Agent[2082]: App did finish launching
Jul 29 19:58:18 MacBook-Pro cDock[19340]: SecTaskLoadEntitlements failed error=22
Jul 29 19:58:18 MacBook-Pro cDock[19340]: App did finish launching

**Comment by w0lfschild** [comment]
Do you have rootless off?

**Comment by dkfiresky** [comment]
Following issues appeared in the logs just before applying any settings:
7/30/15 18:47:38.268 cDock[1576]: SecTaskLoadEntitlements failed error=22
7/30/15 18:48:39.007 Pashua[2051]: SecTaskLoadEntitlements failed error=22
7/30/15 18:49:05.064 osascript[2340]: Performance: Please update this scripting addition to supply a value for ThreadSafe for each event handler: "/Library/ScriptingAdditions/SIMBL.osax"

**Comment by zx8** [comment]
With the release of OS X 10.11 (Public Beta 3), setting `rootless=0` has no effect.

See http://www.tonymacx86.com/el-capitan-desktop-support/169316-os-x-el-capitan-public-beta-3-now-available for info.

**Comment by w0lfschild** [comment]
@zx8 Um... The method I posted to disable rootless still works and should always work. I've already known about the bootarg command being removed for the public release.

**Comment by dkfiresky** [comment]
If cDock was running good with rootless disabled,
after re-enabling rootless again cDock will stop working.

There was some discussion on that rootless disabled mode might be required only for installing some apps, after installation and re-enabling the rootless mode again, they will just work as expected.

**Comment by w0lfschild** [comment]
@dkfiresky I imagine that yes that can be done (at least for now) using https://github.com/norio-nomura/EasySIMBL/issues/26#issuecomment-117028426

I think in addition to implementing that I can remove the need for the Opee framework.

**Comment by Wallyec** [comment]
Wolfgang

Appreciate you keeping me in the loop, but you are way ahead of my expertise, here.

Glad to provide feedback, but I need a simpler approach - look forward to your updates.

Great work!
Thanks
Wally


Wally
-iPad-

**Comment by w0lfschild** [comment]
@Wallyec if you can't figure out how to turn off rootless then cDock (or any other system tweak) will never work for you on 10.11 and beyond.

Booting to recovery: https://support.apple.com/en-us/HT201314

**Comment by w0lfschild** [comment]
I've implemented the move to putting SIMBL in /System/Library and now use my use my own app to install simbl (and remove Opee + /Library SIMBL).

**Comment by EnricoBara** [comment]
Hi I disabled SIP from recovery mode and I still can't apply fullscreeen theme
I'm using OSX 10.11 (15A225f)

2/8/15 08:23:51,013 cDock[272]: SecTaskLoadEntitlements failed error=22
2/8/15 08:23:51,038 cDock[272]: App did finish launching
2/8/15 08:23:52,700 cDock Agent[544]: SecTaskLoadEntitlements failed error=22
2/8/15 08:23:52,759 cDock Agent[544]: App did finish launching
2/8/15 08:23:51,013 cDock[272]: SecTaskLoadEntitlements failed error=22
2/8/15 08:23:51,038 cDock[272]: App did finish launching
2/8/15 08:23:52,700 cDock Agent[544]: SecTaskLoadEntitlements failed error=22
2/8/15 08:23:52,759 cDock Agent[544]: App did finish launching

**Comment by the3ye** [comment]
On Mavericks (fresh install) with updates, for some weird reasons Agent won't install SIMBL

**Comment by EnricoBara** [comment]
Amazing. Just manually installed SIMBL. You should write this on the README
:)

Thank you for your fast reply
Cheers


Il domenica 2 agosto 2015, the3ye <notifications@github.com> ha scritto:

> On Mavericks (fresh install) with updates, for some weird reasons Agent
> won't install SIMBL
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w0lfschild/cDock/issues/16#issuecomment-126994927>.
>


-- 

 | enrico baravelli

**Comment by the3ye** [comment]
Yup, 9.2 is terrible on Mavericks :/ At least for me

Here's 8.2
![screen shot 2015-08-01 at 11 58 01 pm](https://cloud.githubusercontent.com/assets/13607809/9025095/2b57a7c6-38a9-11e5-9903-f58a5ba491e4.png)

**Comment by EnricoBara** [comment]
Wuuuut?? Please don't tell me this isn't a virtual machine LOL  I can't
believe you are keeping Mavericks on a physical pc :D

Il domenica 2 agosto 2015, the3ye <notifications@github.com> ha scritto:

> Yup, 9.2 is terrible on Mavericks :/ At least for me
>
> Here's 8.2
> [image: screen shot 2015-08-01 at 11 58 01 pm]
> <https://cloud.githubusercontent.com/assets/13607809/9025095/2b57a7c6-38a9-11e5-9903-f58a5ba491e4.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w0lfschild/cDock/issues/16#issuecomment-126995533>.
>


-- 

 | enrico baravelli

**Comment by w0lfschild** [comment]
Did you per chance try hitting apply after updating?

**Comment by EnricoBara** [comment]
Yeah of course! Installing SIMBL solved all by the way

**Comment by the3ye** [comment]
> I can't
> believe you are keeping Mavericks on a physical pc :D

Well Yosemite is giving me Kernel Panics on Macbook Unibody 2010 so I'm back on Mavericks.



> Did you per chance try hitting apply after updating?

If you're asking me, 9.2 was fresh install and it didn't work. From all of the themes only the "Blue" one worked as supposed. Removing all cDock files and installing 8.2 fixed issues.

**Comment by AttracksPilot** [comment]
Hi Wolfgang,
Did I understand it right, that you implemented features like: customising indicators and icon reflection and shadows?
Anyhow, I can't find these options in cDock 9.2. Did I do something wrong?
Cheers,
AP

**Comment by w0lfschild** [comment]
None of the new features have a UI. Choose the custom option for more info on creating your own custom dock.

**Comment by AttracksPilot** [comment]
Thanks for your quick reply, Wolfgang.
But is it possible to combine Yose Lite (3D) with the options found in Custom?

Cheers,
AP

**Comment by w0lfschild** [comment]
Yes.

1. Go to ~/Library/Application Support/cDock/themes
2. Duplicate either theme
3. Edit the new theme to include whatever you want

**Comment by w0lfschild** [comment]
Okay I just put out 9.3

That should fix the issues that @the3ye and @EnricoBara were having.

Trimmed some comments in interest of keeping the thread short and on point.

**Comment by AttracksPilot** [comment]
Excellent, Wolfgang!
Thanks for the tip.

Cheers,
AP

**Comment by AttracksPilot** [comment]
Hi Wolfgang,

Great improvements in 9.3!!!
Especially the Reflection tick box and the Create Theme option. It might be a suggestion to include a Shadow tick box as well.

I just noticed that the reflection is not a mirrored one but rotated.
Can you change that. Or can I be of any help?

Thanks again!
Regards,
AP

**Comment by 0ldM4cM4n** [comment]
Excuse me, but how do we download 9.3? I don't see a DMG link anywhere on this site, or a zip file, just all of the various source files. Thanks!

**Comment by allannyholm** [comment]
The Fullscreen theme is borked in this latest release. Worked fine with 9.2. It does not follow the OS bright vs. dark appearance anymore. For instance the bright appearance now has the Fullscreen theme in a matte, dark and with no transparency(frost). It's my favorite of all the themes.

I do have one more SIMBL plugin installed(MenubarDockless) and some other plugins; like XtraFinder but none of these has been changed since the installation of cDock 9.3. I'll roll back just for a short while to 9.2.

**Comment by EnricoBara** [comment]
Yeah same issue with 6.3

Also, I see a little difference between the original dock and the
fullscreen dock, the fullscreen is too high (5px) and when I have an
enlarged window (like photoshop) I can't resize it from bottom because the
window ends under the dock. For me is really important because I use to
work with many opened windows and I usually resize them from top and bottom.
I attach a screenshot with difference






 | enrico baravelli

2015-08-03 11:03 GMT+02:00 Allan Nyholm Nielsen <notifications@github.com>:

**Comment by 0ldM4cM4n** [comment]
Is anyone else having a problem with the ColorfulSidebar plug-in not working? No matter what I try, I cannot get the colored sidebar icons to work. If I check that option on the Extra Settings pane, and go back and check later, "Colored sidebar" is no longer checked under the "Finder" section of that pane.

Also, can someone please verify which files -- if any -- should be installed in:

a. main Library [Example: Macintosh HD/Library]
b. System/Library  [Example: Macintosh HD/System/Library]
c. ~/Library [Example: Macintosh HD/Users/Username/Library]

Another thing: Contrary to what I read on MacUpdate.com, cDock refuses to function fully if I re-enable SIP after the installation.

Finally, after dropping cDock into the Applications folder for the first time, and launching it, it is NOT automatically installing all of its various parts, even if I do a clean install after removing all old parts of both cDock and SIMBL.

For example, I had to manually place a copy of the "cDock.bundle" file into Library/Application Support/SIMBL/Plugins.

Oh, I am now using 9.3 and 15A234d.

Thanks!

**Comment by EnricoBara** [comment]
I don't have ColorfulSidebar in any of the directories you listed.

Now I'm on Yosemite 10.10.4, later today I'll try on El Capitan when I'm
back home but I'm experiencing this problem on Yosemite too.


 | enrico baravelli

2015-08-03 12:57 GMT+02:00 0ldM4cM4n <notifications@github.com>:

**Comment by w0lfschild** [comment]
Thanks for the feedback people.

@EnricoBara I've fixed the overlap issue

@AttracksPilot I've made the icon reflections an X axis flip instead of Z axis

@allannyholm I think I've fixed that issue, the reason it changed was to support OS X 10.9 because it has no frosted glass layer like 10.10+

@0ldM4cM4n 

Colorfulsidebar is not and will not be updated for OS X 10.11, if you want that functionality check out [XtraFinder](https://www.trankynam.com/xtrafinder/).

Have you received this prompt?
![screen shot 2015-08-03 at 9 53 33 am](https://cloud.githubusercontent.com/assets/1920148/9042718/901fdd5a-39c5-11e5-936c-0d6319835831.png)

These are the files of cDock:

    SIMBL
    /System/Library/ScriptingAdditions/SIMBL.osax
    /System/Library/LaunchAgents/net.culater.SIMBL.Agent.plist

    Bundles
    /Library/Application Support/SIMBL/Plugins/cDock.bundle
    /Library/Application Support/SIMBL/Plugins/Colorfulsidebar.bundle

    Themes, Logs and Backups
    ~/Library/Application Support/cDock

    Updater Logs
    ~/Library/Application Support/wUpdater

    Plists
    ~/Library/Preferences/org.w0lf.cDock.plist
    ~/Library/Preferences/com.apple.dock.plist  //This is not created by cDock just modified by it

**Comment by AttracksPilot** [comment]
Thank you very much for all your effort to create this excellent cDock and… maintain it.
Great job!

Regards,
AP aka GJ

**Comment by 0ldM4cM4n** [comment]
Hello Wolfgang. Thank you very much for your response. It is very helpful.

So are you saying that even though "Colorfulsidebar.bundle" is installed in "/Library/Application Support/SIMBL/Plugins/", it is basically useless under 10.11?

In answer to your question, yes, I do recall seeing that prompt and needing to provide my admin password.

I meticulously checked all of the install locations that you noted, and in addition to confirming that I indeed have all of those files and folders in theie proper locations, I also discovered these ADDITIONAL ones. Will they result in problems, and should I remove them? I recall reading that you are currently the install location of certain files, and I am wondering if that is why they are there:

/Library/LaunchAgents/net.culater.SIMBL.Agent.plist
/Library/ScriptingAdditions/SIMBL.osax
~/Library/Application SupportcDock/tmp/com.apple.dock.plist

By "Backups" in "~/Library/Application Support/cDock", are you referring to the two "settings.info" files?

And one final clarification please. Does SIP need to be permanently disabled in order for cDock to work properly, even after installation, or should cDock continue to work normally, even after SIP is re-enabled?

Thanks again for your time and effort. It is much appreciated.


0ldM4cM4n

**Comment by w0lfschild** [comment]
@0ldM4cM4n 

Both

    /Library/ScriptingAdditions/SIMBL.osax
    /Library/LaunchAgents/net.culater.SIMBL.Agent.plist

Should be deleted and the next version will do that.

cDock "should" work with SIP off as long as SIMBL is in place in /System/...

By "Backups" I am referring to the fact that cDock creates a backup of your com.apple.dock.plist every time it applies and saves them in the hidden folder ~/Library/Application Support/cDock/.bak That is what the restore points are in the extra settings window.

At some point I will hide the color sidebar option systems above 10.10

**Comment by 0ldM4cM4n** [comment]
Okay, Wolfgang. I have just manually removed those two files from /Library/.

Should I go ahead and also remove "Colorfulsidebar.bundle" from "/Library/Application Support/SIMBL/Plugins/" being as it is useless under 10.11?

So are you saying that SIP must remain off -- even after installation -- in order for cDock to work properly?

**Comment by w0lfschild** [comment]
@0ldM4cM4n sure but really I don't think it's doing anything.

cDock does work with SIP on.

![screen shot 2015-08-03 at 12 19 21 pm](https://cloud.githubusercontent.com/assets/1920148/9045710/2d78215c-39da-11e5-8eeb-d2ec02ea1dca.png)

v9.3.1 is out and should fix most/all issues in this thread

**Comment by EnricoBara** [comment]
Thank you mate, you are the man! 👍


 | enrico baravelli

2015-08-03 21:23 GMT+02:00 Wolfgang Baird <notifications@github.com>:

**Comment by 0ldM4cM4n** [comment]
Excellent! Except for ColorfulSidebar, cDock is working again under 10.11 beta 5 with SIP enabled after cDock's installation! :)

**Comment by 0ldM4cM4n** [comment]
Still working on 10.11 beta 6.  :)

**Comment by AttracksPilot** [comment]
Hi Wolfgang,

Just two observations:
• When an icon is bouncing, the reflection bounces in the same direction as the icon. Is it possible to change that into the opposite direction?
• The 3D docks seem to lack a divider between the apps and the folders. Can you fix that or is it impossible?

Anyway, thanks again for all your quick fixes!

Cheers,
AP

**Comment by dkfiresky** [comment]
Hey @w0lfschild, thanks for your great work!
Can you please add a button which will open themes folder in Finder?

**Comment by w0lfschild** [comment]
@AttracksPilot 

Icon bouncing: 
Possible - Probably
Will I change it - No

3D divider:
Possible - Yes
Will I "fix" it - Most likely no.

@dkfiresky 

Open themes button:
Probably *not* gonna add it. It's actually really annoying/crappy to add/adjust buttons especially with translations. Maybe I'll add it to the menubar app because that would take all of a few seconds. Either way if you're interested in making themes it's probably easier to just save an alias to the themes folder somewhere easily accessible for you.

**Comment by AttracksPilot** [comment]
Oops!
While I just made a donation… ;-(

**Comment by dkfiresky** [comment]
Hey, @w0lfschild, does dock border is still supported by themes?

**Comment by w0lfschild** [comment]
@dkfiresky Not at the moment but the next release will be adding that back and a few new theme capabilities (Not included in the UI) and performance improvement related fixes.

**Comment by dkfiresky** [comment]
@w0lfschild thanks, glad it going back :+1:

**Comment by w0lfschild** [comment]
https://github.com/w0lfschild/cDock/releases/tag/v9.4

New theme variables:

10.9
- cd_dockSeparator

10.9 +
- cd_borderSize
- cd_borderBGA
- cd_borderBGB
- cd_borderBGG
- cd_borderBGR

10.10 +
- cd_colorIndicator
- cd_indicatorBGA
- cd_indicatorBGB
- cd_indicatorBGG
- cd_indicatorBGR
- cd_sizeIndicator
- cd_indicatorWidth
- cd_indicatorHeight
- cd_darkMode --- New value 3 (inverse of system)

**Comment by 0ldM4cM4n** [comment]
Thank you for another fine update, Wolfgang. :)

**Comment by allannyholm** [comment]
I'm seeing multiple lines of this text in Console:
"07/08/15 23:40:58,735 osascript[30061]: Performance: Please update this scripting addition to supply a value for ThreadSafe for each event handler: "/System/Library/ScriptingAdditions/SIMBL.osax"

I'm thinking that something is wrong?

**Comment by w0lfschild** [comment]
@allannyholm No nothing is wrong but it looks like I could probably stop it from printing that out.

http://superuser.com/a/328721

**Comment by AttracksPilot** [comment]
Why did you label these threads as 'bug', Wolfgang?

**Comment by dkfiresky** [comment]
@AttracksPilot should we ask/write questions to the cDock app, not the issue management?

**Comment by AttracksPilot** [comment]
Sorry, Dmitrly, I don’t understand what you mean.
Did I make a comment about management?

Cheers,
AP

**Comment by dkfiresky** [comment]
@AttracksPilot how your issue related to cDock version 9?

**Comment by AttracksPilot** [comment]
Which issue are you referring to, Dmitrly?

As far as I can see, I only reacted on cDock 9.

**Comment by dkfiresky** [comment]
> AttracksPilot commented 15 hours ago
> Why did you label these threads as 'bug', Wolfgang?

**Comment by AttracksPilot** [comment]
Yes. What’s wrong with that?

**Comment by dkfiresky** [comment]
Just mention it here: issue #26.
cDock discussion chat available on [Gitter](https://gitter.im/apps) :+1:

[![Join the chat at https://gitter.im/w0lfschild/cDock](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/w0lfschild/cDock?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

**Comment by lloyd1981** [comment]
The process must be followed. I use a number of boot drives/partitions for various reasons. The two primary OS are regularly seeded 10.10 and 10.11 (10.10.5 v 2) and 10.11. Beta (15A244d) (10.11.5). Booting through the 10.11 recovery, after turning off Security in the OS, and following the instructions worked.
Lot of recent versions. the one that did first work with 10.11 caused repeated background blackouts, like a neon sign, but that was solved by a reboot and the dock portion worked. No effect on the sidebar. 9.4.1 very stable.
Everything works in 10.10.5. No issues.

Mentioned:
"0ldM4cM4n commented 6 days ago
Still working on 10.11 beta 6. :)"

There have been two available installs of developer line tools (6.4 for 10.10 and 7.0 for 10.11 - the last 7 Aug) but nothing has shown up for 10.11.6. At least for me.

**Comment by w0lfschild** [comment]
Next version is gonna be more bug fixing:

- fix cDock not applying until something caused the dock to redraw if injected after dock loaded
- fix high CPU usage with picture backgrounds
- fix picture backgrounds drawing too low
- fix SIMBL printing Threadsafe message to console 
- fix Colorfulsidebar setting always showing as disabled
- new option `cd_is3D` will extend the dock on OS X 10.10+
- other improvements and fixes

**Comment by dkfiresky** [comment]
@w0lfschild Does ```cd_is3D``` will make what is says (3D dock without background image)? Would be great feature :+1:

**Comment by w0lfschild** [comment]
@dkfiresky Nope cd_is3D is just there to add better "3D" image support as 3D docks are just image backgrounds.

On the note of cd_is3D the next version will have the separator layer make a return to 3D docks. Probably the ability to color and adjust size as well.

![screen shot 2015-08-17 at 9 50 25 pm](https://cloud.githubusercontent.com/assets/1920148/9322582/13e183a4-452a-11e5-99bc-e6fa6b8a2828.png)

I've also made some changes to the bundle that allow dock themes to be changed without restarting the dock. May show up in cDock but not too likely. It's implemented in cDock2 though:

![cdock2 0](https://cloud.githubusercontent.com/assets/1920148/9322779/3c228c3e-452d-11e5-83c8-baa6668b45ed.gif)

**Comment by lloyd1981** [comment]
Regarding the Helper window shown earlier...
I did locate and try to solve the problem of that window opening every time I booted the partition using 10.11.5.

![helper](https://cloud.githubusercontent.com/assets/13730455/9329145/25d15514-457d-11e5-80ca-7d9453520a75.jpg)

 Frustrating because not only an visual irritant, it affected boot load speed. Went to the source: Using the Mac's right click for cDock, I opened the package and reviewed the contents. I moved the cDock-Helper.app to the desktop and no more problems. (cDock 9.5)

Thanks again for all the work

**Comment by Wallyec** [comment]
I found rebooting with SIP OFF ­ Helper window closed and rebooted ­ have
not seen since.
Wally

From:  lloyd1981 <notifications@github.com>
Reply-To:  w0lfschild/cDock
<reply+00cef47defb1d74deafd45b47a0ece51ef8d2b62fc9babc492cf0000000111eadd219
2a169ce05d81405@reply.github.com>
Date:  Tuesday, August 18, 2015 at 7:46 AM
To:  w0lfschild/cDock <cDock@noreply.github.com>
Cc:  Wally Cullen <wallycullen@msn.com>
Subject:  Re: [cDock] cDock 9 (#16)


Regarding the Helper window shown earlier...
I did locate and try to solve the problem of that window opening every time
I booted the partition using 10.11.5.

 <https://cloud.githubusercontent.com/assets/13730455/9329145/25d15514-457d-
11e5-80ca-7d9453520a75.jpg>

Frustrating because not only an visual irritant, it affected boot load
speed. Went to the source: Using the Mac's right click for cDock, I opened
the package and reviewed the contents. I moved the cDock-Helper.app to the
desktop and no more problems. (cDock 9.5)

Thanks again for all the work


Reply to this email directly or view it on GitHub
<https://github.com/w0lfschild/cDock/issues/16#issuecomment-132184573> .

**Comment by w0lfschild** [comment]
@lloyd1981 

It's because in 9.5 I made a change to SIMBL to stop the logging of `osascript[30061]: Performance: Please update this scripting addition to supply a value for ThreadSafe for each event handler: "/System/Library/ScriptingAdditions/SIMBL.osax` to console.

The helper needs SIP/rootless to be off in order to work properly so yes it will always ask if you have SIP on and the app detects that the files the helper installs are not up to date.

**Comment by w0lfschild** [comment]
I've started to put up some binaries of cDock 2. I would appreciate some feedback on the UI and how intuitive or not it is. Also any functionality issues.

[Release](https://github.com/w0lfschild/cDock2/tree/master/release/release.zip)

In it's current state you'll need to at least have opened the original cDock (to set up some directories) for cDock 2 to be able to work.

Here's a rundown of the changes.

------------------------------------------------
Version : 0.9.2
Build : 200
Date : Aug / 27 / 2015

------------------------------------------------

- *GUI rewritten in Objective C*

- Fix

	- Faster window startup
	- App window no longer closes/opens each time something is applied
	- App window now gains focus when clicked in dock
	- App window now able to be selected via Command + tab
	- App window now shows in mission control
	- Spacers are removed from right to left
	
- New

	- Huge control over making your own theme
	- Ability to edit every theme variable in-app
	- SIMBL and Rootless information windows
	- Better about window
	- Dock theming changes without restarting dock
	- Theming and hidden dock settings separated into tabs

- Gone

	- Menubar application
	- Dock plist backups
	- Reset icon cache option
	- Finder Folders on top (Use XtraFinder)
	- Finder Colored sidebar (Use XtraFinder)

- Bundle changes

	- 3D docks can now display a separator
	- 3D docks now extend farther
	- Custom images can be refreshed without restarting the dock
	- Fixed label color applying to layers it shouldn't have
	- Dock theme can be refreshed via CFNotificationCenterPostNotification

- TODO

	- Make sure all directories and files exist
	- Watch theme directory for changes and refresh accordingly
	- Tweak login agent and simbl installer for new app
	- Tooltips 
	- Give dock settings sliders text input
	- Add some buttons
		- Donate 
		- Report
	- Localizations
	- Bundle changes

**Comment by 0ldM4cM4n** [comment]
Hello again Wolfgang,

I am a little confused by your version numbering scheme. According to the Finder and the Get Info window, I already have version 0.9.5 of cDock installed, which I downloaded from GitHub.

So upon receiving this email announcement from you regarding cDock 2, I downloaded the "release.zip" file and installed cDock2 in my Applications folder.

However, both the Finder and Get Info window claim that it is version 0.9.2, which technically makes it older than 0.9.5.

Of course, upon launching it, i see that cDock 2 does indeed have a new UI.

Having said that, I would like to suggest that you adopt a version numbering scheme that is not so confusing. If this is actually cDock 2, shouldn't both the Finder and the Get Info windows say 2.0.0?

One issue I had -- which I have also experienced with previous versions of cDock -- is that upon launching cDock 2 for the first time, it asked me for my admin password about five times before it finally took.

I hope this helps.

**Comment by 0ldM4cM4n** [comment]
I stand to be corrected. The previous version I had installed is 9.5, and not 0.9.5.

If we are now at cDock 2, does this mean that 9.5 is actually 1.9.5?

Does this also mean that the newest version that you just compiled about an hour ago -- 0.9.2 -- is actually 2.0.9.2?

I am just trying to understand how your version numbers work.

Thanks.

**Comment by w0lfschild** [comment]
cDock 2 is a different app thus has it's own versioning. 

This app may or may not be an update for cDock and if it does end up being so it would not be hard to update to something with a lower version number or change the version number to 10 when it's actually ready.

**Comment by dkfiresky** [comment]
@w0lfschild with cDock 2 sometimes changes are not applied until you restart the app several times and re-apply the changes again.

**Comment by w0lfschild** [comment]
@dkfiresky Restarting the app doesn't do anything. Right now there's a 0.5 seconds max rate of changes so if you're dragging around on a color picker or slider it won't apply whatever value you stop dragging at.

**Comment by dkfiresky** [comment]
@w0lfschild it does not apply any values, it just not responding to any action.

**Comment by w0lfschild** [comment]
Okay I'm thinking it had to do with the bundle not overwriting the old version thus the Dock would not be able to receive the notifications sent from cDock2. Pushed out a new test release.

**Comment by Wallyec** [comment]
I like the changes you have made but I consistently get an error in opening the archive when the cDock Helper UPDATE is loaded @startup – twice so far.

I am running OS10.11.4 Beta – and cDock seems to be running fine.

cDock 2 : 0.10.1

Bundle : 0.11.2

SIMBL : 0.9.10

Build Date : Jan / 31 / 2016


I was unable to find a LINK to Support so hopefully this makes it to you.

Thanks for a great program.
Wally
