### ISSUE TITLE
Repeated authorisation requests

### ISSUE THREAD

**Issue by sn4fu** [w0lfschild/cDock#17]
cDock requires repeated authorisations and will work occasionally but require several auths after restart.  

Also I don't seem to have the framework you mention.

I am running iMac with 10.9.5, this has run fine until the latest os update, any ideas, otherwise great app.

/t

**Comment by w0lfschild** [comment]
Try the latest version I've made some changes that should affect this.

**Comment by sn4fu** [comment]
Hi W0lfschild,

Many thanks for your prompt reply, I Jjst tried it and was only asked for 2 oasx auth, Is that normal, certainly much better. I'll see what happens next reboot, m/c busy at the mo.

**Comment by sn4fu** [comment]
Hi W0lfschild,

After reboot at least 4 authorisations to allow osax sending commands. 
I have zip of log files, how to send them?

**Comment by sn4fu** [comment]
Hi W0lfschild,

After reboot at least 4 authorisations to allow osax sending commands. 

Please find attached log files:

sn4fu

**Comment by w0lfschild** [comment]
Try version 9.3

Are you on an admin account?

You can email me the logs from in the app.

**Comment by sn4fu** [comment]
Just sent logs will try 9.3 many thanks.

**Comment by w0lfschild** [comment]
Try 9.3.1

**Comment by sn4fu** [comment]
Hi W0lfschild

OK this one is worse I think!!

Asked twice when I start app and three times when I apply.

Also there are no active app ‘lights’

/snafu

**Comment by w0lfschild** [comment]
Are you an admin account?

**Comment by sn4fu** [comment]
Yes of course, could n’t function as a standard user . . .

/snafu

**Comment by w0lfschild** [comment]
Make sure you have these items

    /System/Library/ScriptingAdditions/SIMBL.osax
    /System/Library/LaunchAgents/net.culater.SIMBL.Agent.plist
    /Library/Application Support/SIMBL/Plugins/

If you don't you're not entering the proper info. Or for one reason or another your account does not have Sudo access.

You should also check the cDock bundle version using terminal:

    defaults read /Library/Application\ Support/SIMBL/Plugins/cDock.bundle/Contents/Info.plist CFBundleVersion

Should be 0.10.12

**Comment by sn4fu** [comment]
All present and correct and version is good . . 

/t

‘sudo works for me normally’

/sn4fu

**Comment by nodarkthings** [comment]
Hi!
I have the exact same problem on 10.9.5: cdock-helper always asks permission at login...
It was ok until v8.3 (I haven't tried all version 9, but 9.2 and 9.3.1 act the same).
cDock bundle version is 0.10.12 but I have neither /System/Library/ScriptingAdditions/SIMBL.osax nor
/System/Library/LaunchAgents/net.culater.SIMBL.Agent.plist installed.
I also tried from the root user, just in case but had errors ("some line missing" kind of alert).
My permissions have been repaired. And it's a pretty fresh install of OSX.
For the time being, I have reverted to v8.3.

**Comment by w0lfschild** [comment]
No I meant /System

What do you see in this file?

    ~/Library/Application Support/cDock/logs/helper.log

**Comment by w0lfschild** [comment]
Please post an image of the missing line alert.

**Comment by sn4fu** [comment]
Sorry no not root user:

Helper log reads:

Removing old files
Installing new files
Starting SIMBL
 
in the screen shot below mail, chrome and safari are all running, but no indicators?

(displayed against black and white)





is that what you meant by Please post an image of the missing line alert.?

/snafu

**Comment by w0lfschild** [comment]
I figured as much. You probably don't have permission do something that the app is trying to do.

What do you get from the command:

    ls -l /Library/Application\ Support/SIMBL/

Should be:

    drwxrwxr-x  7 root  admin  238 Aug  3 16:53 Plugins

Helper log from you isn't helpful because you already manually moved the files in place before you updated so it didn't even run when you updated to 9.3.1

Your image wasn't included with your post.

How about you delete /System/Library/ScriptingAdditions/SIMBL.osax and reopen cDock then post the helper log after it's run.

I'm guessing neither of you are entering account info with sudo access thus nothing is getting written to /System

No indicators it probably because of one of these:

1. Using a theme that's no longer supported
2. Having the same color indicators as your desktop with a transparent dock
3. Using a theme with custom indicators turned on but no custom indicator files

**Comment by sn4fu** [comment]
Hi

 I get almost the same not sure what the “4” is all about.

drwxrwxr-x  4 root  admin  136  3 Aug 20:42 Plugins

Did as you suggested and enclose file. Same behavour as prev.



By the way this is the actual dialogue:




Indicator issue:

Its not the background. . .
I am using transparent theme, so this is displayed both over black and white.





/sn4fu

**Comment by nodarkthings** [comment]
Hi all!
I found the trick: cDock 9.x has to be in /Applications to have permissions to create/install support files!
Mine was in a sub-sub-folder (which was ok before v9.x).
Now all is working fine again. :-)
(but I'd prefer putting it back in its sub-sub-folder, if it was possible... ;-)
I use colored sidebar, Transparent theme with autohide "med", Dim hidden items, icon highlight.

ls -l /Library/Application\ Support/SIMBL/ returns:
total 0
drwxrwxr-x+ 4 503  wheel  136  2 aoû 23:19 Plugins

Just for the sake of science: I still have the alert below when running it from the root user (even in /Applications).
![cdock alert](https://cloud.githubusercontent.com/assets/13633184/9056381/fc1e2c96-3a92-11e5-94e0-4e00e46b8a99.png)

**Comment by w0lfschild** [comment]
Interesting I really don't know why that's the case or why you get that error. Was your application previously in /Applications/Utilities ?

**Comment by nodarkthings** [comment]
No, I classify my apps according to their field in folders (Music, Internet, etc.): cDock was in /Applications/Cosmetics/Docks with fellow apps dealing with the dock. ;-)
There are a few apps that need to be in /Applications such as 1Password, ClickRepair, Snagit v3 (v2 was ok), SpiderOak...

**Comment by sn4fu** [comment]
no, and i think 9.3.1 is worse than 9.3 possibly.

**Comment by w0lfschild** [comment]
Well sn4fu I'm sorry but I don't believe I'm gonna be able to make any changes that is going to fix this for you.

Seeing as the latest version has 7,000+ downloads and you two are the only people who have reported this issue I'm gonna assume it's something specific to your system setup.

I can't even reproduce repeated auth requests when testing on a Guest account.

Very likely that this issue has something to do with your specific setup. Maybe some scripting addition you have installed or problems from updating. From the log you sent me a while back you have files lying around probably back from before 10.6 (The OSAXHandlers key was added in 10.6 and your scripting addition doesn't even have that key so it's older).

> osascript: OpenScripting.framework - scripting addition "/Library/ScriptingAdditions/QXPScriptingAdditions.osax" cannot be used with the current OS because it has no OSAXHandlers entry in its Info.plist.

Maybe it's time to do a clean install. Or at the very least look through your system, if that's there it's quite possible your library folders are full of junk.

The last 10.9 and 10.10 update require stricter permission for injecting into processes and that's why admin credentials are now required for an install. cDock now uses

    /System/Library
    /Library

it used to just run out of

    ~/Library

**Comment by sn4fu** [comment]
Hi W0lfschild,

Thanks for all your efforts with this, I am amazed that you have kept going, Its true this system has been around a while.

I do have a new system on another drive that I am getting into place, but I am terrible with software reg nums etc so have held of the switch.

Maybe its time to sort it all out.

And its working perfectly on yosemite macbook pro with indicators.

Once again many thanks, great software and it does work sort of if I could just get the indicators on . . .

love

/terry

**Comment by nodarkthings** [comment]
On my side: I made a clean install last month but imported my account... I probably use some old conflicting app, I love them so much — won't you believe it: I still love a colored sidebar and a transparent dock, what a fool! :-D (just kidding, of course ;-) )
Indeed, it may be some conflict with XtraFinder, Finderpop, Hazel, Bartender, etc. to name a few... :-/
Thanks for your patience! :-)

P.S.: you mentioned QXPScriptingAdditions.osax, it was installed by QuarkXpress (v7 if I recall well), you can safely delete it if you've got a more recent version.

**Comment by sn4fu** [comment]
Yeah its kinda crazy given the amount of stuff we do on computers that we get so involved in eye candy but I guess from my point of view a transparent dock is a priority

I have had both finder pop and xtrafinder installed at various times, I’ll do some cleaning, already deleted the QXPScriptingAdditions.osax

many thanks

/terry

**Comment by sn4fu** [comment]
Hi just did reboot usual autos required then auto update and this error msg:

Element “tb4” has none of the attributes “default” or “text”. One of these attributes (which are synonyms) must be set.

I have done/am doing  extensive cleaning to no avail, however apart from indicators the dock is transparent and ok.

/t

**Comment by sn4fu** [comment]
Hi W0lfschild,

Indicator lights is a dock preference, god knows how they got turned off!!!

**Comment by w0lfschild** [comment]
Fixed the tb4 issue with 9.4.1

**Comment by sn4fu** [comment]
Thanks, thats fixed that… 

I’m still getting the osax authentication requests, 
I seem to get 3 requests if I have 3 items ticked, does that makes sense, 1 for each script?

Anyway once its going seems fine . . .

**Comment by w0lfschild** [comment]
Are all 3 dialogs the same? What do they look like?

**Comment by sn4fu** [comment]
Hi Wolfgang,

Yes, today 4 times to open crock then twice to apply . . 




As I said crock does work fine, just a hassle every reboot, thanks for your continued attention to this. . .

**Comment by dkfiresky** [comment]
Got same issue with cDock 2. It happened all the time and it asks authorization for about 3-4 times.

**Comment by sn4fu** [comment]
Fine for me, top marks you guys  . . .

/t

**Comment by dominicwa** [comment]
Same here with cDock 2... 4 prompts to authorise the app every time I boot.

**Comment by w0lfschild** [comment]
What do you get when you enter this in terminal?

```bash
locSIMBL=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" /System/Library/ScriptingAdditions/SIMBL.osax/Contents/Info.plist)
curSIMBL=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" /Applications/cDock\ 2.app/Contents/Resources/cDock-Installer.app/Contents/Resources/SIMBL.osax/Contents/Info.plist)
echo -e "Loc: $locSIMBL\nCur: $curSIMBL"
```

Should be:
```
Loc: 0.9.10
Cur: 0.9.10
```

If it's not then you need to disable SIP so you can update SIMBL.
